### ISSUE TITLE
Forum de discussion

### ISSUE THREAD

**Issue by sovmulax** [evaneX0X0/Routier#4]
**Plate-Forme d'échange d'information sur la route en deux étapes :** 

- Sélectionné la commun
- Accès au forum 

**Tâches à éffectuer :** 

- [x] Widget de message 🟥 
- [x] Layout Générale de la méssagerie 💭 
- [x] Vue de Sélection de la commun 🏙️

**Comment by lucgmensah** [comment]
Tu peux m'envoyer une image ? Tu as la maquette non ?
